[package]
name = "fpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clock = "0.3.2"
ilog = "1.0.1"
lazy_static = "1.4.0"
num-traits = "0.2.15"